# Generated by Django 4.2.9 on 2024-03-20 19:25

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=50)),
                ('event_moto', models.CharField(max_length=50)),
                ('event_desc', tinymce.models.HTMLField()),
                ('event_img', models.FileField(default=None, max_length=250, null=True, upload_to='events/')),
            ],
        ),
    ]
