# Generated by Django 4.2.9 on 2024-03-20 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_link', models.CharField(max_length=50)),
                ('team_img', models.FileField(default=None, max_length=250, null=True, upload_to='team/')),
            ],
        ),
    ]
