# Generated by Django 4.2.9 on 2024-03-20 18:42

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='values',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('values_No', models.CharField(max_length=50)),
                ('values_title', models.CharField(max_length=100)),
                ('values_desc', tinymce.models.HTMLField()),
            ],
        ),
    ]
