# Generated by Django 4.2.9 on 2024-03-20 19:15

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='innovation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('innovation_title', models.CharField(max_length=50)),
                ('innovation_desc', tinymce.models.HTMLField()),
                ('innovation_img', models.FileField(default=None, max_length=250, null=True, upload_to='innovations/')),
            ],
        ),
    ]
