# Generated by Django 4.2.9 on 2024-03-20 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_link',
            field=models.CharField(default='Null', max_length=50),
            preserve_default=False,
        ),
    ]
